site_name: OpenGFW
site_url: https://gfw.dev/

theme:
  name: material
  palette:
    - scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: Dark mode
    - scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Light mode

  logo: assets/logo.png
  favicon: assets/logo.png
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.footer
    - navigation.top
    - content.code.copy
    - content.code.annotate
    - announce.dismiss
    - search.suggest
    - search.highlight

markdown_extensions:
  - attr_list
  - admonition
  - md_in_html
  - pymdownx.magiclink
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  generator: false
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/OpGFW
    - icon: fontawesome/brands/github
      link: https://github.com/apernet/OpenGFW

copyright: Copyright &copy; 2020 - 2024 The Hysteria Project

repo_url: https://github.com/apernet/OpenGFW

nav:
  - Home: index.md
  - Docs:
      - Build & Run: docs/build-run.md
      - Rules: docs/rules.md
      - Analyzers: docs/analyzers.md
      - Functions: docs/functions.md
  - GitHub: https://github.com/apernet/OpenGFW

plugins:
  - search
  - glightbox:
      skip_classes:
        - skip-lightbox
  - i18n:
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: zh
          name: 简体中文
          build: true
          nav:
            - 首页: index.md
            - 文档:
                - 构建与运行: docs/build-run.md
                - 规则文件: docs/rules.md
                - 分析器: docs/analyzers.md
                - 内置函数: docs/functions.md
            - GitHub: https://github.com/apernet/OpenGFW
